Repository kontena/mortar, pull requests merged in 2018-09, with the labels that each got.

#26 Warn when there is nothing to do
  lib/mortar/command.rb
Labels: enhancement

#40 Split mortar to fire & yank subcommands
  Gemfile.lock
  bin/mortar
  kontena-mortar.gemspec
  lib/mortar.rb
  lib/mortar/command.rb
  lib/mortar/fire_command.rb
  lib/mortar/mixins/client_helper.rb
  lib/mortar/mixins/resource_helper.rb
  lib/mortar/mixins/tty_helper.rb
  lib/mortar/root_command.rb
  lib/mortar/yank_command.rb
  spec/fire_spec.rb
Labels: enhancement

#29 Fix typo in README.md
  README.md
Labels: chore

#44 Fix docker build
  Dockerfile
Labels: bug, chore

#45 Use k8s-client v0.4.0
  kontena-mortar.gemspec
Labels: enhancement

#48 k8s-client 0.4.1
  kontena-mortar.gemspec
Labels: bug, chore

#47 Document fire & yank
  README.md
Labels: chore

#50 Fix yank exit status when confirmation interrupted
  lib/mortar/yank_command.rb
Labels: bug

#28 Parse files always with erb
  README.md
  lib/mortar/yaml_file.rb
Labels: enhancement
