Repository kontena/mortar, pull requests merged in 2019-09, with the labels that each got.

#108 Update k8s-client to 0.10.4
  Gemfile.lock
  kontena-mortar.gemspec
Labels: chore

#91 Allow to inject custom labels via --label option
  README.md
  lib/mortar/config.rb
  lib/mortar/fire_command.rb
  spec/config_spec.rb
  spec/fire_spec.rb
  spec/fixtures/config/config_labels.yaml
  spec/fixtures/config/config_labels_error.yaml
Labels: enhancement

#109 Release 0.4.3
  Gemfile.lock
  lib/mortar/version.rb
Labels: chore

#111 Release 0.4.4
  lib/mortar/version.rb
Labels: bug

#112 Release 0.4.5
  .drone.yml
  .travis.yml
  Gemfile.lock
  build/drone/ubuntu_xenial.sh
  build/travis/macos.sh
  kontena-mortar.gemspec
  lib/mortar/mixins/resource_helper.rb
  lib/mortar/version.rb
  lib/mortar/yaml_file.rb
Labels: chore
